name: Infection

on:
  workflow_call:
    paths:
      - '**.php'
      - 'infection.json5'
  pull_request:
    paths:
      - '**.php'
      - 'infection.json5'
  push:
    paths:
      - '**.php'
      - 'infection.json5'

jobs:
  run_mutation_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP with PCOV extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov

      - name: Install dependencies using Composer
        uses: ramsey/composer-install@v2

      - name: Execute Infection for mutation testing
        run: composer infection
        continue-on-error: true

