name: Pest

on:
  workflow_call:
  push:
  pull_request:

jobs:
  run_pest_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: List Installed Dependencies
        run: composer show -D

      - name: Run Pest tests with coverage
        run: vendor/bin/pest --coverage  --colors=always --order-by=random
