name: Pint

on:
  workflow_call:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'
  push:
    paths:
      - '**.php'

jobs:
  check_code_styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Pint for code styling
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          preset: laravel
          configPath: "vendor/phonyland/dev-tools/src/pint.json"

      - name: Auto-commit style fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Fix styling"

